USE adoptAdogDB;

CREATE TABLE dog (
    dogName  VARCHAR(255),
    dogImage  VARCHAR(255),
    dogAge  VARCHAR(255),
    gender  VARCHAR(255),
    dogBreed  VARCHAR(255),
    coatLength  VARCHAR(255),
    activityLevel  VARCHAR(255),
    specialNeeds  VARCHAR(255),
    briefBio  VARCHAR(255),
    favorite BOOLEAN
);

INSERT INTO dog (dogName,dogImage,dogAge,gender,dogBreed,coatLength,activityLevel,specialNeeds,briefBio,favorite) 
VALUES ('Thor',
        'https://image.freepik.com/free-photo/german-shorthaired-pointer-dog_100493-508.jpg',
        'Adult',
        'Male',
        'Pointer',
        'Short',
        'High',
        'None',
        'Thor was rescued from the woods with a few acquired survival skills/scars.',
        false),

        ('Ralph',
        'https://i.pinimg.com/originals/7b/d1/51/7bd151c9c47784ddace30feb3c3b11fe.jpg',
        'Adult',
        'Male',
        'Pug',
        'Short',
        'Low',
        'Yes',
        'His owner made the difficult decision that Chuck would be best suited to a new home, where he can continue to grow in a new environment.',
        false),

        ('Charlie',
        'https://lh3.googleusercontent.com/proxy/FP_cAW24DiXsM5bPOqDTa5W99opO8Gncry4KOpxbNuvt6Q-PHjgJsySGhR1mEzd2JnSPu7rfnvbg5tbh_xMeRXGeQyo5MCL7f-2wbRmyJwMdNgWqw5Xxcv3eDeKlg9Kvt701yvnUAHglaPYfeKFPMg',
        'Senior',
        'Male',
        'Havanese',
        'Medium',
        'Low',
        'Yes',
        'Charlie is a second-time rescue from Minneapolis, MN. He was adopted by a family, but unfortunately, they abused him so Charlie is looking for a safe place to call home.',
        false),

        ('Buddy',
        'https://barkpost.com/wp-content/uploads/2019/08/silky-terrier-favorite-dog-toys.jpg',
        'Young',
        'Male',
        'Silky Terrier',
        'Medium',
        'High',
        'None',
        'From Chaska, MN. Scooby-Dooby-Doo! I like to cuddle, how ‘bout with you',
        false),

        ('JoJo',
        'https://image.freepik.com/free-photo/funny-puppy-dog-border-collie-lying-couch-plaid-indoors-lovely-member-family-little-dog-home-warming-blanket-cold-fall-autumn-winter-weather-pet-animal-life-concept_80942-2550.jpg',
        'Young',
        'Female',
        'Border Collie',
        'Long',
        'High',
        'None',
        'Jojo  was left on her own, She was spotted at Harriet Island in St. Paul getting on and off the boats as numbers increased.',
        false),

        ('Maxie',
        'https://i.pinimg.com/originals/c7/45/22/c74522d5be49609deb32bc70d4b4594c.png',
        'Adult',
        'Female',
        'Golden Retriever',
        'Long',
        'High',
        'None',
        'She was found in St. Cloud, running in the middle of the road and She almost got run over.',
        false),

        ('Bailey',
        'https://i.pinimg.com/originals/38/df/d0/38dfd0aaacc5ceaa57a5bb95591d8167.jpg',
        'Puppy',
        'Male',
        'Golden Doodle',
        'Short',
        'High',
        'None',
        ' Bailey is a good boy who just wants to be loved. He’s charming and has the cutest little features.',
        false),

        ('Bella',
        'https://www.aaronmaltesepuppy.com/images/672B2162-2.jpeg',
        'Senior',
        'Female',
        'Maltese',
        'Short',
        'Low',
        'None',
        ' Despite being abandoned, she’s a very friendly little lady who is ready to find her forever home.',
        false),

        ('Teddy',
        'https://images1.americanlisted.com/nlarge/bertram-shih-tzu-senior-adoption-rescue-americanlisted_109574383.jpg',
        'Senior',
        'Male',
        'Shih Tzu',
        'Medium',
        'Low',
        'Yes',
        'His owner passed away and he has been transferred to multiple shelters.',
        false);

CREATE TABLE adopter (
        dogName  VARCHAR(255),
        currentDate DATE,
        contactName VARCHAR(255),
        address VARCHAR(255),
        city VARCHAR(255),
        state VARCHAR(255),
        zip INTEGER,
        phoneNumber VARCHAR(255),
        altPhone VARCHAR(255),
        email VARCHAR(255),
        individualsResiding TEXT,
        agreement BOOLEAN,
        ownRent TINYINT,
        landlord VARCHAR(255),
        homeDescription TEXT,
        experience TEXT,
        petSurrender BOOLEAN,
        currentPetDescription TEXT,
        hoursAlone INTEGER,
        hoursTogether INTEGER,
        dogKept VARCHAR(255),
        dogSleep VARCHAR(255),
        dogTraining VARCHAR(255),
        vet VARCHAR(255)
);   
